[package]
name = "wfc_core"
version = "0.1.0"
authors = ["yanchith <yanchi.toth@gmail.com>"]
edition = "2018"

[dependencies]
fxhash = "0.2.1"
lru = { version = "0.6.5", default-features = false }
rand_core = "0.5.1"
