[package]
name = "wfc_core"
version = "0.1.0"
authors = ["yanchith <yanchi.toth@gmail.com>"]
edition = "2018"

[dependencies]
arrayvec = "0.7.1"
bitflags = "1.2.1"
fxhash = "0.2.1"
oorandom = "11.1.3"
