extern crate cbindgen;

use std::env;

const AUTOGEN_WARNING: &str = "/* This file is autogenerated. Don't modify manually. */";

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_parse_deps(true)
        .with_parse_include(&["wfc_core"])
        .with_autogen_warning(AUTOGEN_WARNING)
        .with_language(cbindgen::Language::Cxx)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("ffi/wfc.hpp");
}
