[package]
name = "wfc_dylib"
version = "0.1.0"
authors = ["yanchith <yanchi.toth@gmail.com>"]
edition = "2018"

[lib]
name = "wfc"
crate-type = ["cdylib"]

[dependencies]
wfc_core = { path = "../wfc_core" }

[build-dependencies]
cbindgen = "0.20.0"
